= Converting DocBook to AsciiDoc
:data-uri:
:icons:

== The Challenge

Converting DocBook to AsciiDoc is much more of a problem than it seems
like it should be footnote:[This is even weirder when you consider how
easy it is to go from AsciiDoc to DocBook.]. There is no perfect or
accepted best solution. Every tool has challenges and problems.

Other groups that have done a format conversion tend to use one of
two processes:

. "Burn it down" - Throw away everything and rewrite it from scratch.
+
This is not practical for the entire documentation set, however
it could be used to reduce the amount of "cruft."  This could also
effectively be used to sunset books that have not been republished
or updated in a long time.

. "Convert, Polish, Review" - use an automated tool; clean up the output;
get it reviewed by several folks.
+
Talking with folks at Red Hat who have done
similar conversions, the current best choice tool is
https://github.com/asciidoctor/docbookrx:[DocBookRx]. It is not
perfect. However, it will at least warn on unconverted tags.
+
After the automated conversion, the work is all review and fixes. It
is recommended that you use `elinks` to create two text files from
the html output of the pre-conversion document and the post-conversion
document. Then you can use `meld` to highlight a lot of the formatting
differences. YMMV.

== Additional Considerations for Fedora

Fedora, like all documentation projects, wants the highest quality
documentation possible.  Markup languages that allow for semantic tagging
can allow documentation to achieve three specific goals that contribute
to quality:

. Consistent presentation of similar types of content
. Higher quality localization through signals to translators and
   localizers about how content is being used
. Automated testing of content for errors and inconsistencies
   footnote:[This is still a fairly new field, however projects like
   https://github.com/emender[Emender] can provide a way forward.]

Therefore, there is still a desire to retain
https://fedoraproject.org/wiki/Docs_Tag_Discussion[some
semantic tagging] after the conversion.  I have
done a study of AsciiDoc and have proposed some
http://www.winglemeyer.org/technology/2016/09/08/semantic-asciidoc/[specific
ideas about how to implement semantic tagging].

Because we should know before we convert the markup format what semantic
tagging is desired, we can theoretically improve our conversion by:

. Converting the existing DocBook tags into the new AsciiDoc semantic
   tagging using text replacement, such as is provided by `sed`.
. Stripping almost all other non-block element tags from the DocBook
   source using a similar process.

These two steps may clean up the DocBook source so much that there may
be minimal conversion failures with most tools.  I have not tested this
directly.
