= Build the Entire Site
:data-uri:
:icons:

== What is in the repository?

For this Proof of Concept (POC), we will use the site configuration
repository, "docs-fp-asciibinder".  This repository contains no content,
therefore everything is stored on the master branch.

This repository is used as a template for building a full AsciiBinder
repository.  The template is used by the `builder.sh` script.  Therefore
these files are very specifically structured and may not be functional
until after the builder has been run.

This is the file tree for the `master` branch:

```
.
|-- _distro_map.yml     <1>
|-- _images             <2>
|   `-- fedora.svg
|-- _javascripts        <2>
|-- _stylesheets        <2>
|   `-- asciibinder.css
|-- _templates          <2>
|   |-- _css.html.erb
|   |-- _nav.html.erb
|   `-- page.html.erb
|-- _topic_map.yml      <3>
|-- builder.sh          <4>
|-- index-en-US.html    <5>
`-- index-master.html   <6>
```

<1> The `_distro_map.yml` is used as a template for building out every
   language.  The text, "en-US" is used as a replaceable in the builder.
<2> These are still generic AsciiBinder files.
<3> The `_topic_map.yml` is dynamically generated by the builder.
   This one is empty.
<4> This is the magic, see below
<5> This is a template single language index file.  The text "en-US"
   is used as a replaceable by the builder.
<6> This is the actual, final, site index page.  For consistency with
   the single book example, it is also ugly.

== How Does it Work?

For the Proof of concept, a builder has been written.  The builder follows
this algorithm to produce a repository that AsciiBinder can process.
This repository is temporary and should be deleted without being pushed
to a remote when the process is finished.

Today, the builder contains a lot of hardcoded values, such as which books
should be included.  These can be refactored out into a configuration
file.

=== Algorithm

Note: Numbers in parenthesis refer to line numbers in the script.  The source is below

This script prepares a full site build.  For this POC, that is:

- two books, the _Installation Guide_ and the _Virtualization Getting
   Started Guide_ in English for all three versions of Fedora: Rawhide,
   Fedora 24, and Fedora 23.
- Japanese translations of all books and versions.
- a French translation of just the _Installation Guide_ for all versions.

The goal is to generate this branch structure:

[options="header"]
|=======
|Language | Version | Branch Name
|English | 23 | f23-adoc-en-US
|English | 24 | f24-adoc-en-US
|English | 24 | master-adoc-en-US
|French | 23 | f23-adoc-fr
|French | 24 | f24-adoc-fr
|French | Rawhide | master-adoc-fr
|Japanese | 23 | f23-adoc-ja
|Japanese | 24 | f24-adoc-ja
|Japanese | Rawhide | master-adoc-ja
|=======

. Setup the Common Content (33-36)
+
This loop shouldn't be a loop right now. :). For now, we just add the
common content to the master-adoc branch so that when we clone the branch
we get common content for "free." This way all content shares a single
version of the common content.

. Build the en-US branches first

  . Create a base version branches (38-42)
  . Create an en-US branch named "<version>-en-US" (50)
  . Add each book into the `_git` directory (53-56)
  . Create the content directories for AsciiBinder by linking in the
    `en-US` dir from each book. (59-62)
  . Extend the `_topic_map.yml` with the topics from each book. (64-68)
  . Clean up includes (really needed later for other languages) (71)
  . Commit this to the language branch (74-75)

. Build out the languages

  . Create a language branch (81-88)
  . Add each book for that language into the `_git` directory (90-94)
  . Link in the content, but change the name of the link to match the
    language. (100)
  . Extend the `_topic_map.yml` with the topics from each book, updating
    the directory name. (102-106)
  . Update include links with the new direction name. (109)
  . Pull the `.po` files from Zanata. footnote:[Warning, this is
    slow.] Store them in the `pot` directory. (106)
  . Apply the translations and update the source files using `po4a`
    (114-121)
  . Commit this to the language branch (123-126)

. Build out the `_distro_map.yml` (133-146)
+
This allows AsciiBinder to know about all of the "version-language" branches.

. Make a final commit (1448-150

. Build the site (152-153)

=== build.sh

```
include::proposal/poc/builder.sh.linenums[]
```

== Looking at the Output

Build the site using the `builder.sh` script from the `master-adoc"
branch:

```
git checkout master-adoc
./builder.sh
```

Note: The Zanata slows, in particular are slow.  This takes approximately
30 minutes to complete.  Some caching will speed this up.

To view the output, use your web browser to open the file
`_package/index.html`.

The ugly index page will let you choose a version to preview.  I suggest
you start with the Rawhide English version.  Because I have not added a
language switcher, to change languages you should use your back button
to return to the index page you opened above.

At some point, take a look at the "Kickstart Syntax Reference" and scroll
down a little bit to see a line that reads:

```
$ ksverdiff -f F23 -t F24
```

This line uses the macros for the current and previous versions of the
product.  Now look at the same file in Fedora 24 and Fedora 23 and see
the difference.

The translations are incomplete, but you can see them in action on
many pages.

A sample build can be found here:
http://www.winglemeyer.org/fedora_docs_proposal/sample/
